#!/bin/bash
# Generate Traefik static/dynamic config for 1Panel (Docker provider + optional ACME).
# 为 1Panel 生成 Traefik 静态/动态配置（Docker 发现 + 可选 ACME）。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

BASE_DIR="$(dirname "${SCRIPT_DIR}")"
DATA_DIR="${BASE_DIR}/data"
DYNAMIC_DIR="${DATA_DIR}/dynamic"

log() { traefik_log "init: $*"; }
fail() { traefik_fail "$*"; }

rand_pass() { openssl rand -base64 18 | tr -d '/+=' | head -c 16; }

htpasswd_apr1() {
    local user="$1" pass="$2"
    local hash
    hash="$(openssl passwd -apr1 "${pass}")"
    printf '%s:%s' "${user}" "${hash}"
}

validate_port() {
    local name="$1" val="$2"
    [[ "$val" =~ ^[0-9]+$ ]] || fail "${name} must be a number"
    (( val >= 1 && val <= 65535 )) || fail "${name} must be between 1 and 65535"
}

traefik_load_env "${BASE_DIR}" || true

PANEL_APP_PORT_HTTP="${PANEL_APP_PORT_HTTP:-8088}"
TRAEFIK_HTTP_PORT="${TRAEFIK_HTTP_PORT:-8880}"
TRAEFIK_HTTPS_PORT="${TRAEFIK_HTTPS_PORT:-8443}"
TRAEFIK_DASHBOARD_USER="${TRAEFIK_DASHBOARD_USER:-admin}"
TRAEFIK_DASHBOARD_PASSWORD="${TRAEFIK_DASHBOARD_PASSWORD:-}"
TRAEFIK_ACME_EMAIL="${TRAEFIK_ACME_EMAIL:-}"

[[ -n "${TRAEFIK_DASHBOARD_USER}" ]] || fail "TRAEFIK_DASHBOARD_USER is required"

validate_port "PANEL_APP_PORT_HTTP" "$PANEL_APP_PORT_HTTP"
validate_port "TRAEFIK_HTTP_PORT" "$TRAEFIK_HTTP_PORT"
validate_port "TRAEFIK_HTTPS_PORT" "$TRAEFIK_HTTPS_PORT"

if [[ "${TRAEFIK_HTTP_PORT}" == "80" || "${TRAEFIK_HTTPS_PORT}" == "443" ]]; then
    log "WARNING: ports 80/443 may conflict with 1Panel OpenResty. Prefer 8880/8443 unless you know what you are doing."
fi

log "Cleaning up containers from any previous failed install ..."
traefik_cleanup_stale_containers
traefik_assert_ports_free

[[ -n "${TRAEFIK_DASHBOARD_PASSWORD}" ]] || TRAEFIK_DASHBOARD_PASSWORD="$(rand_pass)"
DASHBOARD_HTPASSWD="$(htpasswd_apr1 "${TRAEFIK_DASHBOARD_USER}" "${TRAEFIK_DASHBOARD_PASSWORD}")"

mkdir -p "${DYNAMIC_DIR}"
printf '%s\n' "${DASHBOARD_HTPASSWD}" > "${DYNAMIC_DIR}/.htpasswd"
chmod 600 "${DYNAMIC_DIR}/.htpasswd" 2>/dev/null || true

if [[ ! -f "${DATA_DIR}/acme.json" ]]; then
    echo '{}' > "${DATA_DIR}/acme.json"
fi
chmod 600 "${DATA_DIR}/acme.json" 2>/dev/null || true

ACME_BLOCK=""
if [[ -n "${TRAEFIK_ACME_EMAIL}" ]]; then
    ACME_BLOCK=$(cat <<EOF

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TRAEFIK_ACME_EMAIL}
      storage: /acme.json
      httpChallenge:
        entryPoint: web
EOF
)
fi

cat > "${DATA_DIR}/traefik.yml" <<EOF
# Traefik static configuration — generated by 1Panel Traefik app init.sh

api:
  dashboard: true
  insecure: false

log:
  level: INFO

entryPoints:
  traefik:
    address: ":8080"
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: 1panel-network
    watch: true
  file:
    directory: /etc/traefik/dynamic
    watch: true
${ACME_BLOCK}
EOF

cat > "${DYNAMIC_DIR}/dashboard.yaml" <<EOF
http:
  routers:
    dashboard:
      rule: PathPrefix(\`/api\`) || PathPrefix(\`/dashboard\`)
      entryPoints:
        - traefik
      service: api@internal
      middlewares:
        - dashboard-auth
  middlewares:
    dashboard-auth:
      basicAuth:
        usersFile: /etc/traefik/dynamic/.htpasswd
EOF

cat > "${DATA_DIR}/credentials.env" <<EOF
TRAEFIK_DASHBOARD_USER=${TRAEFIK_DASHBOARD_USER}
TRAEFIK_DASHBOARD_PASSWORD=${TRAEFIK_DASHBOARD_PASSWORD}
EOF
chmod 600 "${DATA_DIR}/credentials.env" "${DATA_DIR}/traefik.yml" 2>/dev/null || true

log "Wrote ${DATA_DIR}/traefik.yml, dynamic/dashboard.yaml and dynamic/.htpasswd"
log "Dashboard: http://${TRAEFIK_DASHBOARD_BIND:-127.0.0.1}:${PANEL_APP_PORT_HTTP}/dashboard/ (user: ${TRAEFIK_DASHBOARD_USER})"
log "HTTP entrypoint: :${TRAEFIK_HTTP_PORT}  |  HTTPS entrypoint: :${TRAEFIK_HTTPS_PORT}"
log "Credentials saved to ${DATA_DIR}/credentials.env"
if [[ -n "${TRAEFIK_ACME_EMAIL}" ]]; then
    log "ACME enabled for ${TRAEFIK_ACME_EMAIL}; ensure HTTP :${TRAEFIK_HTTP_PORT} is reachable for http-01"
else
    log "ACME disabled (set TRAEFIK_ACME_EMAIL to enable Let's Encrypt)"
fi
log "Expose backends: add traefik.enable=true labels on containers in network 1panel-network"

exit 0
