#!/bin/bash
# Generate NetBird config for 1Panel (external OpenResty, embedded Dex).
# Aligned with netbirdio/netbird v0.71.4 getting-started.sh (exposed ports mode).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "${SCRIPT_DIR}/lib.sh"

BASE_DIR="$(dirname "${SCRIPT_DIR}")"
DATA_DIR="${BASE_DIR}/data"

log() { netbird_log "init: $*"; }
fail() { netbird_fail "$*"; }

rand_b64() { openssl rand -base64 32; }
rand_b64_nopad() { openssl rand -base64 32 | tr -d '='; }

validate_domain() {
    local d="${1:-}"
    [[ -n "$d" ]] || fail "NETBIRD_DOMAIN is required"
    [[ "$d" != "netbird.example.com" ]] || fail "NETBIRD_DOMAIN cannot be netbird.example.com"
    if [[ "$d" =~ ^https?:// ]]; then
        fail "NETBIRD_DOMAIN must be hostname only (no http://)"
    fi
}

validate_port() {
    local name="$1" val="$2"
    [[ "$val" =~ ^[0-9]+$ ]] || fail "${name} must be a number"
    (( val >= 1 && val <= 65535 )) || fail "${name} must be between 1 and 65535"
}

# --- preflight: load env, cleanup failed install, check ports ---
netbird_load_env "${BASE_DIR}" || true

NETBIRD_DOMAIN="${NETBIRD_DOMAIN:-}"
PANEL_APP_PORT_HTTP="${PANEL_APP_PORT_HTTP:-9080}"
NETBIRD_MGMT_PORT="${NETBIRD_MGMT_PORT:-9081}"
NETBIRD_STUN_PORT="${NETBIRD_STUN_PORT:-3478}"
DATASTORE_ENCRYPTION_KEY="${DATASTORE_ENCRYPTION_KEY:-}"
NETBIRD_RELAY_AUTH_SECRET="${NETBIRD_RELAY_AUTH_SECRET:-}"

if [[ -z "${NETBIRD_DOMAIN}" ]]; then
    fail "NETBIRD_DOMAIN is required. Fill in the domain on the install form (hostname only, e.g. netbird.example.com)."
fi

validate_domain "$NETBIRD_DOMAIN"
validate_port "PANEL_APP_PORT_HTTP" "$PANEL_APP_PORT_HTTP"
validate_port "NETBIRD_MGMT_PORT" "$NETBIRD_MGMT_PORT"
validate_port "NETBIRD_STUN_PORT" "$NETBIRD_STUN_PORT"

log "Cleaning up containers from any previous failed install ..."
netbird_cleanup_stale_containers
netbird_assert_ports_free
netbird_ensure_image_tags_in_env "${BASE_DIR}"
netbird_load_env "${BASE_DIR}" || true

[[ -n "$DATASTORE_ENCRYPTION_KEY" ]] || DATASTORE_ENCRYPTION_KEY="$(rand_b64)"
[[ -n "$NETBIRD_RELAY_AUTH_SECRET" ]] || NETBIRD_RELAY_AUTH_SECRET="$(rand_b64_nopad)"

NETBIRD_HTTP_PROTOCOL="https"
NETBIRD_PORT="443"
TRUSTED_PROXY="127.0.0.1/32"

mkdir -p "${DATA_DIR}/netbird"

cat > "${DATA_DIR}/config.yaml" <<EOF
# Combined NetBird Server Configuration
# Generated by 1Panel netbird app init.sh (v0.71.4)

server:
  listenAddress: ":80"
  exposedAddress: "${NETBIRD_HTTP_PROTOCOL}://${NETBIRD_DOMAIN}:${NETBIRD_PORT}"
  stunPorts:
    - ${NETBIRD_STUN_PORT}
  metricsPort: 9090
  healthcheckAddress: ":9000"
  logLevel: "info"
  logFile: "console"

  authSecret: "${NETBIRD_RELAY_AUTH_SECRET}"
  dataDir: "/var/lib/netbird"

  auth:
    issuer: "${NETBIRD_HTTP_PROTOCOL}://${NETBIRD_DOMAIN}/oauth2"
    signKeyRefreshEnabled: true
    dashboardRedirectURIs:
      - "${NETBIRD_HTTP_PROTOCOL}://${NETBIRD_DOMAIN}/nb-auth"
      - "${NETBIRD_HTTP_PROTOCOL}://${NETBIRD_DOMAIN}/nb-silent-auth"
    cliRedirectURIs:
      - "http://localhost:53000/"

  reverseProxy:
    trustedHTTPProxies:
      - "${TRUSTED_PROXY}"

  store:
    engine: "sqlite"
    encryptionKey: "${DATASTORE_ENCRYPTION_KEY}"
EOF

cat > "${DATA_DIR}/dashboard.env" <<EOF
NETBIRD_MGMT_API_ENDPOINT=${NETBIRD_HTTP_PROTOCOL}://${NETBIRD_DOMAIN}
NETBIRD_MGMT_GRPC_API_ENDPOINT=${NETBIRD_HTTP_PROTOCOL}://${NETBIRD_DOMAIN}
AUTH_AUDIENCE=netbird-dashboard
AUTH_CLIENT_ID=netbird-dashboard
AUTH_CLIENT_SECRET=
AUTH_AUTHORITY=${NETBIRD_HTTP_PROTOCOL}://${NETBIRD_DOMAIN}/oauth2
USE_AUTH0=false
AUTH_SUPPORTED_SCOPES=openid profile email groups
AUTH_REDIRECT_URI=/nb-auth
AUTH_SILENT_REDIRECT_URI=/nb-silent-auth
NGINX_SSL_PORT=443
LETSENCRYPT_DOMAIN=none
EOF

cat > "${DATA_DIR}/openresty-snippet.conf" <<EOF
# NetBird OpenResty snippet — paste into 1Panel site custom config for ${NETBIRD_DOMAIN}
# Dashboard: 127.0.0.1:${PANEL_APP_PORT_HTTP}  |  Server: 127.0.0.1:${NETBIRD_MGMT_PORT}

upstream netbird_dashboard {
    server 127.0.0.1:${PANEL_APP_PORT_HTTP};
    keepalive 10;
}
upstream netbird_server {
    server 127.0.0.1:${NETBIRD_MGMT_PORT};
    keepalive 10;
}

location ~ ^/(relay|ws-proxy/) {
    proxy_pass http://netbird_server;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 1d;
}

location ~ ^/(signalexchange\.SignalExchange|management\.ManagementService)/ {
    grpc_pass grpc://netbird_server;
    grpc_set_header Host \$host;
    grpc_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    grpc_read_timeout 1d;
    grpc_send_timeout 1d;
    grpc_socket_keepalive on;
}

location ~ ^/(api|oauth2)/ {
    proxy_pass http://netbird_server;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
}

location / {
    proxy_pass http://netbird_dashboard;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
}
EOF

chmod 600 "${DATA_DIR}/config.yaml" "${DATA_DIR}/dashboard.env" 2>/dev/null || true

log "Wrote ${DATA_DIR}/config.yaml and dashboard.env"
log "Ports: dashboard 127.0.0.1:${PANEL_APP_PORT_HTTP}, api 127.0.0.1:${NETBIRD_MGMT_PORT}, stun udp ${NETBIRD_STUN_PORT}"
log "OpenResty snippet: ${DATA_DIR}/openresty-snippet.conf"
log "After install: HTTPS site for ${NETBIRD_DOMAIN}, then https://${NETBIRD_DOMAIN}/setup"

exit 0
