additionalProperties:
    key: Traefik
    name: Traefik
    tags:
        - Tool
        - WebSite
    shortDescZh: 云原生反向代理
    shortDescEn: Cloud-native reverse proxy
    type: website
    crossVersionUpdate: true
    limit: 0
    website: https://traefik.io/
    github: https://github.com/traefik/traefik
    document: https://doc.traefik.io/traefik/
